# -*- coding: utf-8 -*-
"""Netflix_NLP_Recommender_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lzvM0BlctnwxJlaQMYuDzCnnVv6YljC9
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

# Load dataset
df = pd.read_csv("netflix_titles.csv")
df = df[['title', 'description']].dropna().drop_duplicates()
df = df.reset_index()

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['description'])
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

def recommend(title, cosine_sim=cosine_sim):
    title = title.lower()
    if title not in df['title'].str.lower().values:
        return ["Sorry, show not found."]
    idx = df[df['title'].str.lower() == title].index[0]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:6]
    show_indices = [i[0] for i in sim_scores]
    return df['title'].iloc[show_indices].tolist()

recommend("Stranger Things")

